#!/bin/sh
cachedir=${XDG_CACHE_HOME:-"$HOME/.cache"}
if [ -d "$cachedir" ]; then
	cache=$cachedir/rumenu_run
else
	cache=$HOME/.rumenu_cache # if no xdg dir, fall back to dotfile in ~
fi
(
	IFS=:
	if rutest -dqr -n "$cache" $PATH; then
		rutest -flx $PATH | sort -u | tee "$cache" | rumenu "$@"
	else
		rumenu "$@" < "$cache"
	fi
) | ${SHELL:-"/bin/sh"} &
